name: NPM Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Configure npm auth and scope
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.npmzero }}" > ~/.npmrc
          echo "@sapdev.eu:registry=https://registry.npmjs.org/" >> ~/.npmrc

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npmzero }}
